### ISSUE TITLE
Add library skeleton

### ISSUE THREAD

**Issue by apcountryman** [apcountryman/picolibrary#5]
Add library skeleton which consists of the following:
- [ ] CMake rules for build the library (`source/CMakeLists.txt`).
- [ ] Library namespace and associated header/source files (`include/picolibrary.h`, and `source/picolibrary.cc`).
- [ ] Library testing facilities namespace (`picolibrary::Testing`) and associated header/source files (`include/picolibrary/testing.h`, and `source/picolibrary/testing.cc`).
- [ ] Library unit testing facilities namespace (`picolibrary::Testing::Unit`) and associated header/source files (`include/picolibrary/testing/unit.h`, and `source/plib/testing/unit.cc`).
- [ ] Library interactive testing facilities namespace (`picolibrary::Testing::Interactive`) and associated header/source files (`include/picolibrary/testing/interactive.h`, and `source/plib/testing/interactive.cc`).

The following must be completed before this can procede:
- [ ] [Add build system infrastructure](https://github.com/apcountryman/picolibrary/issues/1).
- [ ] [Add documentation infrastructure](https://github.com/apcountryman/picolibrary/issues/2).
- [ ] [Add unit testing infrastructure](https://github.com/apcountryman/picolibrary/issues/3).
- [ ] [Add interactive testing infrastructure](https://github.com/apcountryman/picolibrary/issues/4).
